### ISSUE TITLE
ADS deploy does not make in linux. (sourcing pcds_conda)

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/ads-ioc#34]
```
(pcds-3.1.0) [adpai@psbuild-rhel7-01 ioc-plc-lfe-vac]$ make
-----------------------------------------------------------
Build path: /reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac/.pytmc_build
PLC: plc_lfe_vac
IOC name: ioc-plc-lfe-vac
PYTMC_OPTS:
PROJECT_PATH: ../../plc_lfe_vac/plc_lfe_vac.tsproj
Absolute project path:  /reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/plc_lfe_vac/plc_lfe_vac.tsproj
-----------------------------------------------------------


mkdir -p "/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac/.pytmc_build"
make[1]: Entering directory `/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac'
Executing pytmc stcmd: creating st.cmd...
cd "/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac/.pytmc_build" && \
        pytmc stcmd \
        --name "ioc-plc-lfe-vac" \
        --plc "plc_lfe_vac" \
        --template-path "/reg/g/pcds/epics/ioc/common/ads-ioc/R0.2.0/iocBoot/templates" \
        --template "st.cmd.template" \
        --hashbang "/reg/g/pcds/epics/ioc/common/ads-ioc/R0.2.0/bin/rhel7-x86_64/adsIoc" \
        --only-motor \
        -p "PREFIX" \
         \
        "/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/plc_lfe_vac/plc_lfe_vac.tsproj" > st.cmd
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.1.0/bin/pytmc", line 11, in <module>
    load_entry_point('pytmc==2.5.0', 'console_scripts', 'pytmc')()
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.1.0/lib/python3.6/site-packages/pytmc/bin/pytmc.py", line 92, in main
    func(**kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.1.0/lib/python3.6/site-packages/pytmc/bin/stcmd.py", line 215, in main
    project = parse(tsproj_project)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.1.0/lib/python3.6/site-packages/pytmc/parser.py", line 38, in parse
    tree = lxml.etree.parse(f)
  File "src/lxml/etree.pyx", line 3519, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/plc_lfe_vac/plc_lfe_vac.tsproj", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
make[1]: *** [st.cmd] Error 1
make[1]: Leaving directory `/reg/g/pcds/epics-dev/adpai/lcls-plc-lfe-vac/plc_lfe_vac/iocBoot/ioc-plc-lfe-vac'
make: *** [build] Error 2
(pcds-3.1.0) [adpai@psbuild-rhel7-01 ioc-plc-lfe-vac]$
```

**Comment by klauer** [comment]
There was a change with `pytmc` command-line arguments + the makefile that is causing this. I think we should take a forward-looking approach, but still make a hotfix so that tsproj won't get overwritten when ads-ioc + pytmc versions aren't matched appropriately.
